[workspace]
members = ["leptos_hotkeys", "wasm-keys", "examples/demo", "examples/ssr-demo"]
resolver = "2"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
